### ISSUE TITLE
构建的时候报错了

### ISSUE THREAD

**Issue by talentyao** [shynome/wechat_web_devtools#3]
![image](https://user-images.githubusercontent.com/1400187/64254798-b3a95e00-cf52-11e9-92f3-9ef61db975fa.png)

**Comment by shynome** [comment]
只要把报错的这行删掉就好了

**Comment by shynome** [comment]
重新构建了下, 没有复现. 这个问题是你的 `dorowu/ubuntu-desktop-lxde-vnc:bionic` 镜像太旧了, 需要执行下面步骤之一:
- 执行 `docker pull dorowu/ubuntu-desktop-lxde-vnc:bionic` 
- (个人推荐) 用 `dorowu/ubuntu-desktop-lxde-vnc:bionic@sha256:80f4f30431bd8dcbfdcd80a00602c22884cf74842b19197670201550dd18391e` 替换掉 `Dockerfile` 开头的 `dorowu/ubuntu-desktop-lxde-vnc:bionic` 

因为我这边不能写死容器镜像的 sha256 值, 避免上级镜像修复了问题这边又要再修复一边, 所以需要你按照上述建议进行操作
