### ISSUE TITLE
先进入容器再调用 cli 会报错

### ISSUE THREAD

**Issue by UZIhuhuhu** [shynome/wechat_web_devtools#4]
```sh
module.js:540
    throw err;
    ^

Error: Cannot find module '/wxdt/dist/package.nw/js/common/cli/index.js'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

**Comment by shynome** [comment]
这个时候可能是初始化还没有完成, 初始化根据机器性能差别很大, 我的机器需要 16s 服务器上就要将近 1m. 
查看是否初始化完成的话, 可以看日志 `docker logs -f wxdt`.
保证初始化完成后执行命令的脚本是这个: https://github.com/shynome/wechat_web_devtools/blob/master/bin/docker-entrypoint.sh

**Comment by UZIhuhuhu** [comment]
> 这个时候可能是初始化还没有完成, 初始化根据机器性能差别很大, 我的机器需要 16s 服务器上就要将近 1m.
> 查看是否初始化完成的话, 可以看日志 `docker logs -f wxdt`.
> 保证初始化完成后执行命令的脚本是这个: https://github.com/shynome/wechat_web_devtools/blob/master/bin/docker-entrypoint.sh

Thx.
